exports.seed = async function(knex) {
  await knex('users').insert([
    {
      auth0_id: 'auth0|abc12345',
      first_name: 'Emma',
      last_name: 'Johnson',
      user_name: 'emma.j',
      phone_number: '64 21 1234567',
      address: '123 Main St',
      city: 'Auckland',
      country: 'New Zealand',
      zip_code: '1010',
      email_address: 'emma.j@example.com',
      created_at: '2023-07-21 9:15:00',
      is_admin: false
    },
    {
      auth0_id: 'auth0|def67890',
      first_name: 'Liam',
      last_name: 'Smith',
      user_name: 'liam_smith',
      phone_number: '64 21 9876543',
      address: '456 Maple Ave',
      city: 'Wellington',
      country: 'New Zealand',
      zip_code: '6011',
      email_address: 'liam.smith@example.com',
      created_at: '2023-07-20 14:30:00',
      is_admin: false
    },
    {
      auth0_id: 'auth0|xyz45678',
      first_name: 'Olivia',
      last_name: 'Williams',
      user_name: 'ollie_w',
      phone_number: '64 27 555888',
      address: '789 Oak Rd',
      city: 'Christchurch',
      country: 'New Zealand',
      zip_code: '8011',
      email_address: 'olivia.w@example.com',
      created_at: '2023-07-19 11:45:00',
      is_admin: false
    },
    {
      auth0_id: 'auth0|pqr98765',
      first_name: 'Noah',
      last_name: 'Jones',
      user_name: 'noah_j',
      phone_number: '64 22 3334444',
      address: '321 Elm Court',
      city: 'Dunedin',
      country: 'New Zealand',
      zip_code: '9016',
      email_address: 'noah.j@example.com',
      created_at: '2023-07-18 16:00:00',
      is_admin: false
    },
    {
      auth0_id: 'auth0|lmn65432',
      first_name: 'Ava',
      last_name: 'Brown',
      user_name: 'ava.b',
      phone_number: '64 27 1112222',
      address: '654 Pine Lane',
      city: 'Hamilton',
      country: 'New Zealand',
      zip_code: '3204',
      email_address: 'ava.b@example.com',
      created_at: '2023-07-17 10:20:00',
      is_admin: false
    },
    {
      auth0_id: 'auth0|ghi32109',
      first_name: 'Oliver',
      last_name: 'Taylor',
      user_name: 'olly_t',
      phone_number: '64 21 4447777',
      address: '987 Birch Blvd',
      city: 'Tauranga',
      country: 'New Zealand',
      zip_code: '3110',
      email_address: 'oliver.t@example.com',
      created_at: '2023-07-16 12:40:00',
      is_admin: false
    },
    {
      auth0_id: 'auth0|uvw54321',
      first_name: 'Isla',
      last_name: 'Davis',
      user_name: 'isla.d',
      phone_number: '64 27 8889999',
      address: '654 Willow Drive',
      city: 'Napier',
      country: 'New Zealand',
      zip_code: '4110',
      email_address: 'isla.d@example.com',
      created_at: '2023-07-15 8:10:00',
      is_admin: false
    },
    {
      auth0_id: 'auth0|hij23456',
      first_name: 'Jack',
      last_name: 'Evans',
      user_name: 'jack_e',
      phone_number: '64 22 7776666',
      address: '789 Rose Street',
      city: 'Palmerston North',
      country: 'New Zealand',
      zip_code: '4410',
      email_address: 'jack.evans@example.com',
      created_at: '2023-07-14 17:50:00',
      is_admin: false
    },
    {
      auth0_id: 'auth0|klm78901',
      first_name: 'Charlotte',
      last_name: 'Wilson',
      user_name: 'char_w',
      phone_number: '64 21 2223333',
      address: '123 Ivy Lane',
      city: 'Nelson',
      country: 'New Zealand',
      zip_code: '7010',
      email_address: 'charlotte.w@example.com',
      created_at: '2023-07-13 13:25:00',
      is_admin: false
    },
    {
      auth0_id: 'auth0|bcd34567',
      first_name: 'Leo',
      last_name: 'Moore',
      user_name: 'leo_m',
      phone_number: '64 27 9990000',
      address: '987 Poplar Close',
      city: 'Rotorua',
      country: 'New Zealand',
      zip_code: '3010',
      email_address: 'leo.moore@example.com',
      created_at: '2023-07-12 9:55:00',
      is_admin: false
    }
  ]);
};
